buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22"
        classpath "org.jlleitschuh.gradle:ktlint-gradle:12.1.0"
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
